import type { CrisisBoss } from '../../types';

/** World 5 crisis: a site whose data looks too clean. Four rounds, 100 s, pool 115 s. */
export const w5Crisis: CrisisBoss = {
  id: 'w5-crisis',
  worldId: 'w5',
  title: 'Site 12 is perfect',
  situation: [
    'Site 12 has enrolled 30 patients, twice any other site, with no missed visits, no queries and no adverse events. The monitor is due there tomorrow. The central data team has a bad feeling.',
    'Monitor, query, code, and triage what surfaces. Four roles, one site.',
  ],
  rounds: [
    {
      id: 'r-cra',
      roleId: 'cra-monitor',
      seconds: 25,
      brief: "You're the Monitor at Site 12. Three records. Which one cannot be real?",
      meterHit: { integrity: -15 },
      game: {
        engine: 'spot-the-impostor',
        prompt: 'Which record was not generated by a real visit?',
        seconds: 25,
        targetLabel: 'the fabricated record',
        cards: [
          {
            id: 'rec-real',
            title: 'Participant 1203',
            lines: [
              "Clinic note in the doctor's handwriting, dated",
              'Lab report from the hospital lab',
              'Visit 5 two days late, explained',
            ],
            conceptId: 'sdv',
            explanation: 'Messy, dated, human. Real visits look like this.',
            consequence: 'Real records have imperfections; perfection is the warning sign.',
          },
          {
            id: 'rec-fake',
            title: 'Participant 1211',
            lines: [
              'Six visits, all exactly 28 days apart',
              'Identical blood pressure at every visit',
              'No source notes; "entered from memory"',
            ],
            impostor: true,
            conceptId: 'protocol-deviation',
            explanation:
              'Identical values, perfect intervals, no source. This is not a patient; it is a spreadsheet.',
            consequence:
              "Fabricated data can invalidate a site's entire contribution and end an investigator's career.",
          },
          {
            id: 'rec-busy',
            title: 'Participant 1218',
            lines: [
              'Source notes present for every visit',
              'One query open about a lab unit',
              'Consent re-signed after an amendment',
            ],
            conceptId: 'monitoring-visit',
            explanation: 'Queries and re-consent are signs of a site doing the work.',
            consequence: 'Suspecting the honest site wastes the visit.',
          },
        ],
      },
      emits: [
        {
          key: 'local.fraud',
          tags: ['found', 'missed'],
          defaultTag: 'missed',
          outcomes: [{ tag: 'found', when: { accused: 'rec-fake' } }],
        },
      ],
    },
    {
      id: 'r-dm',
      roleId: 'clinical-data-manager',
      seconds: 25,
      brief: "You're the Data Manager. Which of these Site 12 patterns gets a query, and which is fine?",
      meterHit: { integrity: -10 },
      game: {
        engine: 'bucket-sort',
        prompt: 'Query it, or leave it?',
        seconds: 25,
        buckets: [
          { id: 'query', label: 'Raise a query' },
          { id: 'fine', label: 'No query' },
        ],
        cards: [
          {
            id: 'same-bp',
            text: 'Eleven patients with blood pressure 120/80 at every visit',
            bucketId: 'query',
            conceptId: 'data-cleaning',
            explanation:
              'Real measurements vary. Identical values across patients are a fabrication pattern.',
            consequence: "Unqueried patterns become the inspector's first exhibit.",
          },
          {
            id: 'no-ae',
            text: 'Thirty patients, a year of dosing, zero adverse events',
            bucketId: 'query',
            conceptId: 'data-query',
            explanation:
              'Zero events in thirty patients is not clean data; it is data that was not collected.',
            consequence: 'A site reporting no events hides the safety signal you exist to find.',
          },
          {
            id: 'late-visit',
            text: 'One visit three days outside its window, documented',
            bucketId: 'fine',
            conceptId: 'monitoring-visit',
            explanation: 'A documented late visit is normal and already recorded as a minor deviation.',
            consequence: 'Querying normal imperfections buries the real pattern.',
          },
        ],
      },
    },
    {
      id: 'r-code',
      roleId: 'medical-coder',
      seconds: 25,
      brief: "You're the Coder. The re-monitoring turned up events that were never entered. Code them.",
      meterHit: { integrity: -10 },
      game: {
        engine: 'match-pairs',
        prompt: 'Match verbatim to term.',
        seconds: 25,
        pairs: [
          {
            id: 'c-dizzy',
            left: '"Dizzy when standing up"',
            right: 'Dizziness postural',
            conceptId: 'medical-coding',
            explanation: 'The verbatim gives the trigger; the term keeps it.',
            consequence: 'Losing "postural" loses a clue about blood pressure.',
          },
          {
            id: 'c-yellow',
            left: '"Eyes looked yellow for a week"',
            right: 'Jaundice',
            conceptId: 'medical-coding',
            explanation: 'Yellow eyes are jaundice, a liver sign the safety team must see.',
            consequence: 'Coding this as "eye discolouration" hides a liver signal.',
          },
          {
            id: 'c-para',
            left: 'Took "paracetamol for a headache"',
            right: 'Paracetamol (WHODrug: analgesic)',
            conceptId: 'whodrug',
            explanation: 'Medicines go to WHODrug, with their class.',
            consequence: 'Uncoded medicines hide interactions.',
          },
        ],
      },
    },
    {
      id: 'r-pv',
      roleId: 'pharmacovigilance-associate',
      seconds: 25,
      brief: "You're Pharmacovigilance. The jaundice case was never reported. Triage what you now know.",
      meterHit: { safety: -15 },
      game: {
        engine: 'bucket-sort',
        prompt: 'Classify each report.',
        seconds: 25,
        buckets: [
          { id: 'ae', label: 'AE' },
          { id: 'sae', label: 'SAE' },
          { id: 'susar', label: 'SUSAR' },
        ],
        cards: [
          {
            id: 'jaundice',
            text: 'Jaundice, admitted for three days, investigator now says "probably related"',
            bucketId: 'susar',
            conceptId: 'susar',
            explanation:
              'Serious, unexpected, related. The 15-day clock started weeks ago; report today with an explanation.',
            consequence: 'A SUSAR discovered late must still be reported, with the delay explained.',
          },
          {
            id: 'dizzy',
            text: 'Postural dizziness, resolved, no treatment',
            bucketId: 'ae',
            conceptId: 'adverse-event',
            explanation: 'Not serious. Record and follow.',
            consequence: 'Over-reporting hides the case that matters.',
          },
          {
            id: 'appendix',
            text: 'Appendicitis, surgery, recovered; not related to the drug',
            bucketId: 'sae',
            conceptId: 'sae',
            explanation:
              'Hospitalisation makes it serious; unrelated means no expedited report, but the 24-hour site report still applied.',
            consequence: 'Serious means serious, whatever caused it.',
          },
        ],
      },
      variants: [
        {
          when: { 'local.fraud': 'missed' },
          patch: {
            brief:
              "You're Pharmacovigilance. The fabricated record was signed off, so the jaundice case surfaced from a hospital letter instead. Triage what you now know.",
            meterHit: { safety: -20 },
          },
        },
      ],
    },
  ],
  resolution: {
    success: {
      id: 'w5-crisis-success',
      title: 'Too clean to be true',
      paragraphs: [
        'The fabricated record was found, the patterns were queried, the missing events were coded, and the jaundice case reached the regulator with an honest explanation of the delay.',
        'Site 12 is closed and its data are flagged. The trial is smaller and true.',
      ],
      mayaStatus: 'Her site was not Site 12. She never knew.',
    },
    partial: {
      id: 'w5-crisis-partial',
      title: 'Half uncovered',
      paragraphs: [
        'Some of the problem is on the record. The rest will surface at inspection, later and worse.',
        'Have another go: each round is one role looking at the same too-perfect site.',
      ],
      mayaStatus: 'Continuing her visits.',
    },
    fail: {
      id: 'w5-crisis-fail',
      title: 'Signed off',
      paragraphs: [
        'The visit report was signed, the patterns went unqueried, and the jaundice case was found by an inspector reading hospital letters.',
        "The site's data are excluded, the study loses a year, and the finding follows the sponsor into every future inspection.",
      ],
      mayaStatus: 'Heard the study was delayed. Nobody said why.',
    },
  },
};
