import type { RoleRef } from './types';

/**
 * Every role in the game, in play order. Full Role Cards live in worlds/<world>/roles.ts.
 * This index exists so hand-off references and the world map can refer to roles that
 * are not yet fully written (their world is still 'planned').
 */
export const roleIndex: RoleRef[] = [
  // World 1 — Diagnosis & Discovery
  {
    id: 'patient-advocate',
    title: 'Patient & Patient Advocate',
    shortTitle: 'Patient Advocate',
    employer: 'patient',
    worldId: 'w1',
    badgeIcon: 'heart',
  },
  {
    id: 'discovery-scientist',
    title: 'Research Scientist (Discovery)',
    shortTitle: 'Discovery Scientist',
    employer: 'sponsor',
    worldId: 'w1',
    badgeIcon: 'flask',
  },
  {
    id: 'preclinical-toxicologist',
    title: 'Preclinical Scientist / Toxicologist',
    shortTitle: 'Toxicologist',
    employer: 'sponsor',
    worldId: 'w1',
    badgeIcon: 'mouse',
  },
  {
    id: 'cmc-scientist',
    title: 'CMC / Formulation Scientist',
    shortTitle: 'CMC Scientist',
    employer: 'sponsor',
    worldId: 'w1',
    badgeIcon: 'pill',
  },

  // World 2 — Designing the Trial
  {
    id: 'clinical-scientist',
    title: 'Clinical Scientist / Medical Director',
    shortTitle: 'Medical Director',
    employer: 'sponsor',
    worldId: 'w2',
    badgeIcon: 'document',
  },
  {
    id: 'biostatistician',
    title: 'Biostatistician',
    shortTitle: 'Biostatistician',
    employer: 'sponsor',
    worldId: 'w2',
    badgeIcon: 'chart',
  },
  {
    id: 'regulatory-affairs-specialist',
    title: 'Regulatory Affairs Specialist',
    shortTitle: 'Reg Affairs',
    employer: 'sponsor',
    worldId: 'w2',
    badgeIcon: 'stamp',
  },
  {
    id: 'irb-member',
    title: 'IRB / Ethics Committee Member',
    shortTitle: 'IRB Member',
    employer: 'regulator',
    worldId: 'w2',
    badgeIcon: 'scale',
  },
  {
    id: 'portfolio-lead',
    title: 'Portfolio / Finance Lead',
    shortTitle: 'Portfolio Lead',
    employer: 'sponsor',
    worldId: 'w2',
    badgeIcon: 'coins',
  },

  // World 3 — Study Start-Up
  {
    id: 'clinical-project-manager',
    title: 'Clinical Project Manager',
    shortTitle: 'Project Manager',
    employer: 'cro',
    worldId: 'w3',
    badgeIcon: 'calendar',
  },
  {
    id: 'site-startup-specialist',
    title: 'Site Feasibility & Start-up Specialist',
    shortTitle: 'Site Start-up',
    employer: 'cro',
    worldId: 'w3',
    badgeIcon: 'globe',
  },
  {
    id: 'clinical-supply-manager',
    title: 'Clinical Supply Manager',
    shortTitle: 'Supply Manager',
    employer: 'sponsor',
    worldId: 'w3',
    badgeIcon: 'truck',
  },
  {
    id: 'edc-programmer',
    title: 'Clinical Database / EDC Programmer',
    shortTitle: 'EDC Programmer',
    employer: 'vendor',
    worldId: 'w3',
    badgeIcon: 'database',
  },
  {
    id: 'irt-specialist',
    title: 'IRT / RTSM Specialist',
    shortTitle: 'IRT Specialist',
    employer: 'vendor',
    worldId: 'w3',
    badgeIcon: 'dice',
  },
  {
    id: 'systems-validation-engineer',
    title: 'Clinical Systems & Validation Engineer',
    shortTitle: 'Validation Eng.',
    employer: 'vendor',
    worldId: 'w3',
    badgeIcon: 'shield',
  },
  {
    id: 'tmf-specialist',
    title: 'TMF Specialist',
    shortTitle: 'TMF Specialist',
    employer: 'cro',
    worldId: 'w3',
    badgeIcon: 'folder',
  },

  // World 4 — Phase I
  {
    id: 'principal-investigator',
    title: 'Principal Investigator',
    shortTitle: 'Investigator',
    employer: 'site',
    worldId: 'w4',
    badgeIcon: 'stethoscope',
  },
  {
    id: 'study-coordinator',
    title: 'Clinical Research Coordinator / Study Nurse',
    shortTitle: 'Study Coordinator',
    employer: 'site',
    worldId: 'w4',
    badgeIcon: 'clipboard',
  },
  {
    id: 'clinical-pharmacologist',
    title: 'Clinical Pharmacologist',
    shortTitle: 'Pharmacologist',
    employer: 'sponsor',
    worldId: 'w4',
    badgeIcon: 'curve',
  },
  {
    id: 'safety-review-committee',
    title: 'Safety Review Committee Member',
    shortTitle: 'Safety Committee',
    employer: 'sponsor',
    worldId: 'w4',
    badgeIcon: 'committee',
  },

  // World 5 — Phase II
  {
    id: 'recruitment-specialist',
    title: 'Patient Recruitment Specialist',
    shortTitle: 'Recruitment',
    employer: 'vendor',
    worldId: 'w5',
    badgeIcon: 'megaphone',
  },
  {
    id: 'cra-monitor',
    title: 'Clinical Research Associate (Monitor)',
    shortTitle: 'CRA / Monitor',
    employer: 'cro',
    worldId: 'w5',
    badgeIcon: 'magnifier',
  },
  {
    id: 'clinical-data-manager',
    title: 'Clinical Data Manager',
    shortTitle: 'Data Manager',
    employer: 'cro',
    worldId: 'w5',
    badgeIcon: 'database',
  },
  {
    id: 'medical-coder',
    title: 'Medical Coder',
    shortTitle: 'Medical Coder',
    employer: 'cro',
    worldId: 'w5',
    badgeIcon: 'tag',
  },
  {
    id: 'pharmacovigilance-associate',
    title: 'Drug Safety / Pharmacovigilance Associate',
    shortTitle: 'Drug Safety',
    employer: 'sponsor',
    worldId: 'w5',
    badgeIcon: 'siren',
  },

  // World 6 — Phase III
  {
    id: 'global-study-manager',
    title: 'Global Study Manager',
    shortTitle: 'Global Study Mgr',
    employer: 'sponsor',
    worldId: 'w6',
    badgeIcon: 'globe',
  },
  {
    id: 'central-monitor',
    title: 'Central Monitor / Risk-Based Monitoring Analyst',
    shortTitle: 'Central Monitor',
    employer: 'cro',
    worldId: 'w6',
    badgeIcon: 'radar',
  },
  {
    id: 'qa-auditor',
    title: 'QA Auditor',
    shortTitle: 'QA Auditor',
    employer: 'sponsor',
    worldId: 'w6',
    badgeIcon: 'shield',
  },
  {
    id: 'dsmb-member',
    title: 'DSMB Member',
    shortTitle: 'DSMB Member',
    employer: 'regulator',
    worldId: 'w6',
    badgeIcon: 'committee',
  },
  {
    id: 'database-lock-lead',
    title: 'Data Manager + Biostatistician (Database Lock)',
    shortTitle: 'Database Lock',
    employer: 'cro',
    worldId: 'w6',
    badgeIcon: 'lock',
  },
  {
    id: 'statistical-programmer',
    title: 'Statistical Programmer',
    shortTitle: 'Stat Programmer',
    employer: 'cro',
    worldId: 'w6',
    badgeIcon: 'code',
  },
  {
    id: 'medical-writer',
    title: 'Medical Writer',
    shortTitle: 'Medical Writer',
    employer: 'vendor',
    worldId: 'w6',
    badgeIcon: 'pen',
  },

  // World 7 — Submission & Approval
  {
    id: 'regulatory-affairs-lead',
    title: 'Regulatory Affairs Lead',
    shortTitle: 'Reg Affairs Lead',
    employer: 'sponsor',
    worldId: 'w7',
    badgeIcon: 'stamp',
  },
  {
    id: 'submission-publisher',
    title: 'Regulatory Publishing / Submission Specialist',
    shortTitle: 'Submission Tech',
    employer: 'vendor',
    worldId: 'w7',
    badgeIcon: 'link',
  },
  {
    id: 'health-authority-reviewer',
    title: 'Health Authority Reviewer (FDA / EMA)',
    shortTitle: 'HA Reviewer',
    employer: 'regulator',
    worldId: 'w7',
    badgeIcon: 'scale',
  },
  {
    id: 'inspection-readiness-lead',
    title: 'Inspection Readiness Lead',
    shortTitle: 'Inspection Lead',
    employer: 'sponsor',
    worldId: 'w7',
    badgeIcon: 'briefcase',
  },
  {
    id: 'labeling-specialist',
    title: 'Labeling Specialist',
    shortTitle: 'Labeling',
    employer: 'sponsor',
    worldId: 'w7',
    badgeIcon: 'tag',
  },

  // World 8 — Launch & Beyond
  {
    id: 'manufacturing-supply-lead',
    title: 'Manufacturing & Supply Chain Lead',
    shortTitle: 'Manufacturing',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'factory',
  },
  {
    id: 'market-access-specialist',
    title: 'Market Access / HEOR Specialist',
    shortTitle: 'Market Access',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'coins',
  },
  {
    id: 'brand-marketing-manager',
    title: 'Brand / Product Marketing Manager',
    shortTitle: 'Brand Manager',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'megaphone',
  },
  {
    id: 'medical-science-liaison',
    title: 'Medical Science Liaison',
    shortTitle: 'MSL',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'handshake',
  },
  {
    id: 'sales-representative',
    title: 'Sales Representative',
    shortTitle: 'Sales Rep',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'briefcase',
  },
  {
    id: 'signal-detection-scientist',
    title: 'Post-Market Pharmacovigilance / Signal Detection Scientist',
    shortTitle: 'Signal Detection',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'radar',
  },
  {
    id: 'rwe-lead',
    title: 'Real-World Evidence / Phase IV Lead',
    shortTitle: 'RWE Lead',
    employer: 'sponsor',
    worldId: 'w8',
    badgeIcon: 'telescope',
  },
];

export const roleRefById: Record<string, RoleRef> = Object.fromEntries(roleIndex.map((r) => [r.id, r]));
