import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 2. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w2-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'clinical-scientist': [
    q(
      'clinical-scientist',
      1,
      'protocol',
      'What is a clinical trial protocol?',
      [
        'The written plan for the whole study, fixed before it starts',
        'The list of drugs a patient takes',
        "A regulator's approval letter",
        'The final study report',
      ],
      'The protocol states the question, endpoints, eligibility, design and procedures before the trial begins.',
      'Studies without a clear protocol cannot be reproduced or trusted.',
    ),
    q(
      'clinical-scientist',
      2,
      'primary-endpoint',
      'A primary endpoint is…',
      [
        'The single pre-specified measurement that answers the main question',
        'The last visit of the study',
        'The dose that worked best',
        'The site that enrolled most patients',
      ],
      'One endpoint, chosen in advance, so the result cannot be picked afterwards.',
      'Choosing endpoints after seeing the data is a form of cheating regulators look for.',
    ),
    q(
      'clinical-scientist',
      3,
      'phase-1',
      'The main question of a Phase I study is…',
      [
        'Is it safe, and how does the body handle it?',
        'Does it cure the disease?',
        'Is it cheaper than the standard?',
        'Will doctors prescribe it?',
      ],
      'Phase I studies safety, tolerability and pharmacokinetics, usually in healthy volunteers.',
      'Expecting efficacy from Phase I sets up the wrong design and the wrong hopes.',
    ),
    q(
      'clinical-scientist',
      4,
      'eligibility-criteria',
      'Why do protocols limit who can join?',
      [
        'To protect vulnerable people and keep the answer interpretable',
        'To make the study cheaper',
        'To exclude anyone who might complain',
        'Because regulators pick the patients',
      ],
      'Criteria keep people at special risk out and keep the population consistent enough to analyse.',
      'Criteria that are too loose endanger people; too tight and nobody can be enrolled.',
    ),
  ],
  biostatistician: [
    q(
      'biostatistician',
      1,
      'statistical-power',
      'Statistical power is…',
      [
        'The chance the study detects an effect that is really there',
        "The size of the drug's effect",
        'How many sites a study uses',
        "The regulator's confidence",
      ],
      'Power is usually set at 80–90 percent. Below that, real effects are often missed.',
      'Underpowered trials fail for arithmetic reasons and take the drug down with them.',
    ),
    q(
      'biostatistician',
      2,
      'randomization',
      'Why randomize patients between treatment and placebo?',
      [
        'So the groups are alike except for the treatment',
        'So sicker patients get the drug',
        'To save money',
        'Because patients prefer it',
      ],
      'Random assignment balances known and unknown differences, so the comparison is fair.',
      'Without randomization, differences between groups can be mistaken for a drug effect.',
    ),
    q(
      'biostatistician',
      3,
      'sap',
      'The statistical analysis plan (SAP) must be finalized…',
      [
        'Before the data are unblinded',
        'After the results are known',
        'Only if the regulator asks',
        'At the end of the marketing campaign',
      ],
      'Fixing the analysis first stops anyone from choosing the method that gives the answer they want.',
      'Analyses chosen after unblinding are not trusted by regulators or journals.',
    ),
    q(
      'biostatistician',
      4,
      'sample-size',
      'Doubling the sample size mainly…',
      [
        'Increases the chance of detecting a real effect',
        'Makes the drug work better',
        'Removes the need for a placebo',
        'Shortens the study',
      ],
      'More patients mean less noise and more power, at the cost of time and money.',
      'Choosing the size by budget instead of power is a common design failure.',
    ),
  ],
  'regulatory-affairs-specialist': [
    q(
      'regulatory-affairs-specialist',
      1,
      'ind',
      'In the US, what allows a company to start dosing people?',
      [
        'An IND that the FDA has not objected to within 30 days',
        'A patent',
        'A signed contract with a hospital',
        'A press release',
      ],
      'The Investigational New Drug application becomes active after 30 days unless the FDA places a hold.',
      'Dosing without an active IND is illegal.',
    ),
    q(
      'regulatory-affairs-specialist',
      2,
      'cta',
      'The EU equivalent of the IND is the…',
      [
        'Clinical Trial Application (CTA)',
        'Certificate of Analysis',
        'Common Technical Agreement',
        'Consent Tracking Archive',
      ],
      'In the EU a CTA is submitted through a single portal and must be authorised before the trial starts.',
      'Mixing up the two pathways leads to missed regional requirements.',
    ),
    q(
      'regulatory-affairs-specialist',
      3,
      'pre-ind-meeting',
      'A pre-submission meeting with the regulator is for…',
      [
        'Agreeing what the filing must contain before you assemble it',
        "Negotiating the drug's price",
        'Getting the study approved on the spot',
        'Meeting the patients',
      ],
      'It aligns expectations early and prevents avoidable questions and holds.',
      'Filing cold is the top cause of avoidable delays.',
    ),
    q(
      'regulatory-affairs-specialist',
      4,
      'irb',
      'Regulator approval of a trial means the site can dose the first volunteer.',
      [
        'False: ethics committee approval is also required',
        'True',
        'True, if the sponsor pays a fee',
        'True in the US only',
      ],
      'Both the regulator and the IRB or ethics committee must approve before anyone is dosed.',
      'Dosing without ethics approval is a critical GCP violation.',
    ),
  ],
  'irb-member': [
    q(
      'irb-member',
      1,
      'informed-consent',
      'Informed consent is valid only if the person…',
      [
        'Understands the purpose, risks and rights and agrees freely',
        'Signs on the right line',
        'Is paid enough',
        'Has a medical degree',
      ],
      'Consent is a process of understanding, not a signature.',
      'Consent obtained without understanding can invalidate a whole study.',
    ),
    q(
      'irb-member',
      2,
      'therapeutic-misconception',
      'Therapeutic misconception means a participant…',
      [
        'Believes the study is designed to treat them personally',
        'Refuses treatment',
        'Misreads a dose label',
        'Thinks the placebo is dangerous',
      ],
      'Research is designed to answer a question, not to treat each participant. Consent must make that clear.',
      'Promising benefit that does not exist is the classic consent failure.',
    ),
    q(
      'irb-member',
      3,
      'undue-influence',
      'Which payment arrangement raises an undue influence concern?',
      [
        'A large bonus paid only to those who complete the study',
        'Modest payment per visit',
        'Reimbursing travel costs',
        'No payment at all',
      ],
      'Completion bonuses pressure people to stay in a study when they should leave.',
      'Undue influence undermines the voluntariness of consent.',
    ),
    q(
      'irb-member',
      4,
      'irb',
      'What can an ethics committee do with a protocol?',
      [
        'Approve it, require changes, or reject it',
        'Only approve it',
        'Only reject it',
        "Change the drug's dose",
      ],
      'Committees have real authority: nothing starts at a site without their approval.',
      'Treating the committee as a formality is how sites get shut down.',
    ),
  ],
  'portfolio-lead': [
    q(
      'portfolio-lead',
      1,
      'go-no-go',
      'A go / no-go decision is…',
      [
        'A milestone review deciding whether a programme continues',
        "A regulator's inspection",
        'A sales target',
        'The final approval',
      ],
      'At each stage gate, data, cost and probability of success decide whether the money keeps flowing.',
      'Programmes that skip honest stage gates burn money on molecules that should have stopped.',
    ),
    q(
      'portfolio-lead',
      2,
      'attrition',
      'Roughly what fraction of drugs entering human trials are eventually approved?',
      ['About 1 in 10', 'About 9 in 10', 'About half', 'Almost all'],
      'Most programmes fail, so a portfolio spreads risk across several.',
      'Betting everything on one molecule is how companies disappear.',
    ),
    q(
      'portfolio-lead',
      3,
      'go-no-go',
      'Why keep a financial reserve in a programme budget?',
      [
        'Because surprises like a clinical hold are normal',
        'To pay bonuses',
        'Regulators require it',
        'To buy equipment',
      ],
      'A reserve turns a crisis into a delay instead of a cancellation.',
      'Programmes without reserves die at the first setback.',
    ),
    q(
      'portfolio-lead',
      4,
      'development-timeline',
      'A typical new medicine takes about how long from discovery to approval?',
      ['10 to 15 years', '1 to 2 years', '3 to 4 years', '30 years'],
      'Discovery, preclinical work, three phases of trials and review add up to more than a decade.',
      'Underestimating the timeline leads to budgets that run out mid-trial.',
    ),
  ],
};

export const w2Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
