import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 3. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w3-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'clinical-project-manager': [
    q(
      'clinical-project-manager',
      1,
      'study-startup',
      'Which comes first in study start-up?',
      ['Site feasibility', 'Site initiation visit', 'Database lock', 'First patient dosed'],
      'You cannot contract, supply or train a site you have not found yet.',
      'Out-of-order start-up wastes money on sites that never enrol.',
    ),
    q(
      'clinical-project-manager',
      2,
      'risk-management-plan',
      'A risk management plan lists…',
      [
        'What could go wrong, how likely, and what will be done',
        "Every patient's side effects",
        "The drug's price",
        'Staff holidays',
      ],
      'Risks are identified, rated and given owners and responses before they happen.',
      'Trials without risk plans turn small problems into long delays.',
    ),
    q(
      'clinical-project-manager',
      3,
      'study-startup',
      'The most common cause of missing the first-patient date is…',
      ['Contracts and ethics approvals', 'The drug not working', 'Bad weather', 'Too many patients'],
      'Paperwork, not science, is what usually slips.',
      'Underestimating start-up paperwork ruins timelines.',
    ),
    q(
      'clinical-project-manager',
      4,
      'go-no-go',
      'Why keep contingency money in a start-up budget?',
      [
        'Something always goes wrong, such as a failed shipment',
        'To pay bonuses',
        'Regulators require it',
        'To buy more drug',
      ],
      'Contingency turns a surprise into a delay instead of a crisis.',
      'No contingency means the first excursion eats the vendor budget.',
    ),
  ],
  'site-startup-specialist': [
    q(
      'site-startup-specialist',
      1,
      'site-feasibility',
      'A site says it can enrol "as many as you need". You should…',
      [
        'Verify with a qualification visit',
        'Sign the contract immediately',
        'Assign it half the study',
        'Ignore it',
      ],
      'Over-promises are common; visits check the reality.',
      'Trusting survey numbers is why enrolment forecasts miss by half.',
    ),
    q(
      'site-startup-specialist',
      2,
      'site-contract',
      'A site cannot open without…',
      [
        'A signed agreement and ethics approval',
        'A press release',
        'A finished study report',
        'A marketing plan',
      ],
      'Contract, budget and ethics approval are prerequisites to activation.',
      'Sites activated without contracts create legal and payment problems.',
    ),
    q(
      'site-startup-specialist',
      3,
      'site-selection',
      'The best site candidate has…',
      [
        'Patients, trained staff and time to focus',
        'The biggest building',
        'The lowest price',
        'The most competing trials',
      ],
      'Selection weighs patient access, experience and bandwidth.',
      'Sites chosen on price alone deliver few patients.',
    ),
    q(
      'site-startup-specialist',
      4,
      'site-initiation-visit',
      'A site may begin screening patients after…',
      [
        'Its site initiation visit',
        'Its feasibility survey',
        'The first shipment is ordered',
        'The database is designed',
      ],
      'The SIV confirms training and readiness.',
      'Screening before initiation produces deviations from day one.',
    ),
  ],
  'clinical-supply-manager': [
    q(
      'clinical-supply-manager',
      1,
      'temperature-excursion',
      "A shipment's logger shows it got too warm. The drug is…",
      [
        'Quarantined until a stability expert rules',
        'Used if it looks fine',
        'Thrown away immediately',
        'Shipped to another site',
      ],
      'Excursions go to QA for a decision; the drug may or may not be usable.',
      'Dosing from an excursion is a safety risk and a deviation.',
    ),
    q(
      'clinical-supply-manager',
      2,
      'qp-release',
      'In the EU, who must certify a batch before release?',
      ['A Qualified Person (QP)', 'The site pharmacist', 'The patient', 'The courier'],
      'QP certification is a legal requirement for investigational drug in the EU.',
      'Unreleased drug shipped into the EU must be quarantined.',
    ),
    q(
      'clinical-supply-manager',
      3,
      'clinical-supply',
      'Drug accountability records show…',
      [
        'Every unit received, dispensed, returned and destroyed',
        "The drug's chemical formula",
        'Patient names',
        "The sponsor's profit",
      ],
      'Accountability is unit-level tracking from depot to destruction.',
      'Gaps in accountability are a standard inspection finding.',
    ),
    q(
      'clinical-supply-manager',
      4,
      'blinding',
      'Study drug and placebo kits should…',
      [
        'Look identical and carry only kit numbers',
        'Be labelled by treatment',
        'Be different colours',
        'Be stored in different rooms',
      ],
      'Identical, numbered kits keep everyone blind.',
      'Readable treatment labels unblind the site.',
    ),
  ],
  'edc-programmer': [
    q(
      'edc-programmer',
      1,
      'ecrf',
      'An eCRF should collect…',
      [
        'Exactly what the protocol needs',
        'Everything the site could measure',
        'Only patient names',
        'Whatever the site prefers',
      ],
      'Over-collection creates queries and burnout; under-collection makes eligibility unverifiable.',
      'Bloated forms produce worse data, not more.',
    ),
    q(
      'edc-programmer',
      2,
      'edit-check',
      'An edit check fires…',
      [
        'At data entry, when a value is impossible or out of range',
        'At the end of the study',
        'Only during audits',
        'When the regulator asks',
      ],
      'Checks catch problems in seconds instead of months.',
      'Relying on monitors alone lets bad data sit for months.',
    ),
    q(
      'edc-programmer',
      3,
      'audit-trail',
      'A clinical database must record for every change…',
      [
        'Who, when, old value, new value and why',
        'Only the new value',
        "The patient's consent",
        'Nothing; changes are not allowed',
      ],
      'This is the audit trail required by Part 11 and Annex 11.',
      'Data without an audit trail is not accepted by regulators.',
    ),
    q(
      'edc-programmer',
      4,
      'cdisc',
      'Using CDISC standards at data entry mainly…',
      [
        'Saves re-mapping the data before submission',
        'Makes the drug work better',
        'Removes the need for a statistician',
        'Speeds up shipping',
      ],
      'Standard terminology from the start avoids error-prone re-mapping later.',
      'Non-standard data delays submissions.',
    ),
  ],
  'irt-specialist': [
    q(
      'irt-specialist',
      1,
      'irt',
      "The IRT system's main jobs are…",
      [
        'Randomize patients and assign kits while keeping the blind',
        'Write the protocol',
        'Pay the sites',
        'Analyse the results',
      ],
      'IRT handles allocation and supply without revealing treatment.',
      'Manual allocation breaks the blind and runs sites out of drug.',
    ),
    q(
      'irt-specialist',
      2,
      'stratification',
      'Stratified randomization keeps groups balanced…',
      [
        'Within each site or severity level',
        'Only at the sponsor',
        'By patient preference',
        'By alphabetical order',
      ],
      'Balance within strata makes the comparison fair at each level.',
      'Imbalance within sites weakens the analysis.',
    ),
    q(
      'irt-specialist',
      3,
      'emergency-unblinding',
      'Emergency unblinding must be…',
      [
        'Possible for patient safety and logged every time',
        'Impossible under any circumstances',
        'Done by the sponsor for planning',
        'Announced to all sites',
      ],
      'A doctor may need to know the treatment; the record shows it happened and why.',
      "Untraceable unblinding puts the study's data in question.",
    ),
    q(
      'irt-specialist',
      4,
      'randomization',
      'Why is "alternate drug and placebo" not acceptable?',
      [
        'It is predictable, so staff can steer patients',
        'It is too expensive',
        'Regulators prefer coin flips',
        'It uses too much drug',
      ],
      'Predictable allocation lets bias in and breaks the blind.',
      'Predictable schemes bias the result.',
    ),
  ],
  'systems-validation-engineer': [
    q(
      'systems-validation-engineer',
      1,
      'csv',
      'Computer system validation proves…',
      [
        'The system does what it is supposed to, with documented evidence',
        'The drug is effective',
        'The site is enrolling',
        'The budget is correct',
      ],
      'Requirements, tests, fixes and sign-off form the evidence.',
      'Unvalidated systems produce data regulators can reject.',
    ),
    q(
      'systems-validation-engineer',
      2,
      'access-control',
      'A shared login for all site staff is a problem because…',
      ['Actions cannot be attributed to one person', 'It costs more', 'It is slower', 'Patients dislike it'],
      'Part 11 requires every action to be attributable.',
      'Shared accounts are a critical inspection finding.',
    ),
    q(
      'systems-validation-engineer',
      3,
      'part-11',
      '21 CFR Part 11 covers…',
      ['Electronic records and electronic signatures', 'Drug pricing', 'Animal welfare', 'Advertising'],
      'It sets the rules for trusting electronic records like paper.',
      'Ignoring Part 11 invalidates electronic data.',
    ),
    q(
      'systems-validation-engineer',
      4,
      'audit-trail',
      'An audit trail that can be switched off is…',
      ['Not acceptable', 'Fine if switched back on later', 'Standard practice', 'Required by law'],
      'Audit trails must be continuous and tamper-proof.',
      'Any gap invalidates the data window.',
    ),
  ],
  'tmf-specialist': [
    q(
      'tmf-specialist',
      1,
      'tmf',
      'The Trial Master File exists so that…',
      [
        'An inspector can reconstruct how the trial was run',
        'Patients can read their data',
        'The sponsor can advertise',
        'Sites get paid',
      ],
      'Every essential document, filed by zone and date.',
      'If it is not in the TMF, it did not happen.',
    ),
    q(
      'tmf-specialist',
      2,
      'essential-documents',
      'Which is an essential document?',
      ['The IRB approval letter', 'A group chat', 'A lunch receipt', 'A news article'],
      'Approvals, contracts, protocol versions and training records are essential.',
      'Missing approvals make every patient a potential violation.',
    ),
    q(
      'tmf-specialist',
      3,
      'tmf',
      'Filing documents "later" is a problem because…',
      [
        'The pile grows and inspectors ask for documents by date',
        'Documents expire',
        'It saves time',
        'It is required',
      ],
      'Contemporaneous filing keeps the file inspection-ready.',
      '"We have it somewhere" is a finding.',
    ),
    q(
      'tmf-specialist',
      4,
      'gcp',
      'Staff training certificates prove…',
      [
        'People were qualified before they worked on patients',
        'The drug is safe',
        'The site is profitable',
        'The study is finished',
      ],
      'Inspectors check training dates against first-patient dates.',
      'Untrained staff invalidate the data they collected.',
    ),
  ],
};

export const w3Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
