import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 4. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w4-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'principal-investigator': [
    q(
      'principal-investigator',
      1,
      'screen-failure',
      "A volunteer is two years over the protocol's age limit. They are…",
      [
        'A screen failure',
        'Eligible if they feel well',
        'Eligible with a note',
        'Eligible if the sponsor is busy',
      ],
      'Criteria are applied exactly as written.',
      'Age deviations are a common inspection finding.',
    ),
    q(
      'principal-investigator',
      2,
      'protocol-clarification',
      'The protocol does not say whether a vitamin counts as a "daily medicine". You should…',
      [
        'Ask the sponsor for a written clarification',
        'Decide yourself',
        'Enrol and note it later',
        'Exclude everyone taking anything',
      ],
      'A written clarification keeps every site consistent.',
      'Sites deciding grey areas alone produce data that cannot be pooled.',
    ),
    q(
      'principal-investigator',
      3,
      'consent-process',
      'A candidate signed the consent form before the study was explained. The consent is…',
      [
        'Not valid; repeat the process properly',
        'Valid because it is signed',
        'Valid if a witness signs too',
        'Valid after the first dose',
      ],
      'Consent is a process of understanding, not a signature.',
      'Consent out of order is a critical GCP finding.',
    ),
    q(
      'principal-investigator',
      4,
      'source-document',
      'Source documents are…',
      [
        'The original records study data is verified against',
        "The sponsor's marketing plan",
        'The drug labels',
        "The investigator's CV",
      ],
      'Lab reports and clinic notes are the source; the eCRF is a copy.',
      'Data without source cannot be verified.',
    ),
  ],
  'study-coordinator': [
    q(
      'study-coordinator',
      1,
      'pk-sampling',
      'A PK blood draw is scheduled at 4 hours post-dose. Drawing it at 5 hours…',
      ['Distorts the concentration curve', 'Is fine', 'Improves accuracy', 'Is required'],
      'Timed draws must land in their window or the point is lost.',
      'Late draws mislead the pharmacologist.',
    ),
    q(
      'study-coordinator',
      2,
      'adverse-event',
      'A volunteer mentions a headache. You should…',
      [
        'Record it as an adverse event with onset, severity and action',
        'Ignore it; headaches are common',
        'Tell them to take an aspirin and move on',
        'Wait to see if it gets worse',
      ],
      'Every complaint is an adverse event until judged otherwise.',
      'Unrecorded events make the safety picture look cleaner than it is.',
    ),
    q(
      'study-coordinator',
      3,
      'consent-process',
      'Consent should be confirmed…',
      [
        'At every visit, not just the first',
        'Once, at screening',
        'Only if the protocol changes',
        'Never after dosing',
      ],
      'Participation stays voluntary throughout.',
      "Assuming consent once is forever ignores the participant's rights.",
    ),
    q(
      'study-coordinator',
      4,
      'source-document',
      'Data should be entered into the eCRF from…',
      [
        'Source documents recorded at the time',
        'Memory at the end of the week',
        "The sponsor's expectations",
        "The previous volunteer's form",
      ],
      'Contemporaneous source records are the basis of every entry.',
      'Data from memory is data the monitor cannot verify.',
    ),
  ],
  'clinical-pharmacologist': [
    q(
      'clinical-pharmacologist',
      1,
      'exposure',
      'Exposure describes…',
      [
        'How much drug reaches the blood over time',
        'How many capsules were taken',
        'The dose in milligrams',
        'The price per dose',
      ],
      'Peak level and area under the curve measure what the body actually sees.',
      'Judging safety by dose alone ignores that people differ.',
    ),
    q(
      'clinical-pharmacologist',
      2,
      'half-life',
      'A half-life of 8 hours means…',
      [
        'The drug level halves every 8 hours',
        'The drug lasts 8 hours',
        'Half the dose is absorbed',
        'The drug works after 8 hours',
      ],
      'Half-life sets how often a drug must be dosed and how long it lingers.',
      'Misreading half-life leads to accumulation or under-dosing.',
    ),
    q(
      'clinical-pharmacologist',
      3,
      'dose-escalation',
      'Why escalate doses in small steps?',
      [
        'Because the model is a guess and each step adds safety data',
        'To save money',
        'Regulators like slow studies',
        'To keep volunteers longer',
      ],
      'Each cohort tests the prediction before the next step.',
      'Skipping steps has caused serious harm in real studies.',
    ),
    q(
      'clinical-pharmacologist',
      4,
      'stopping-rule',
      'A good stopping rule…',
      [
        'Names a grade of event and an exposure limit in advance',
        'Says "stop when uncomfortable"',
        'Is decided after the data',
        'Is optional',
      ],
      'Rules fixed before the data take the decision out of the moment.',
      'Vague rules are why escalations go one cohort too far.',
    ),
  ],
  'safety-review-committee': [
    q(
      'safety-review-committee',
      1,
      'clinical-hold',
      'A clinical hold is…',
      [
        "A regulator's order to stop or not start a study",
        'A pause chosen by a volunteer',
        'A delay in drug shipping',
        'A holiday',
      ],
      'In the US the FDA imposes holds; EU authorities can suspend a trial similarly.',
      'Dosing during a hold is illegal.',
    ),
    q(
      'safety-review-committee',
      2,
      'stopping-rule',
      'One volunteer has a rising liver enzyme. The committee should…',
      [
        'Pause escalation and investigate',
        'Dose the next cohort; one case is not a pattern',
        'Terminate the programme immediately',
        'Wait for a second case',
      ],
      'The stopping rule exists for exactly this.',
      'Dosing through a signal is the finding regulators never forgive.',
    ),
    q(
      'safety-review-committee',
      3,
      'sentinel-dosing',
      'Sentinel dosing means…',
      [
        'Dosing one volunteer first and waiting before the rest',
        'Dosing the whole cohort at once',
        'Dosing only at night',
        'Dosing the investigator first',
      ],
      'A sentinel limits how many people are exposed if the first dose goes wrong.',
      'Dosing a whole cohort at once multiplies the harm of a surprise.',
    ),
    q(
      'safety-review-committee',
      4,
      'dose-escalation',
      'After each cohort, the committee decides to…',
      ['Escalate, repeat, pause or stop', 'Publish the results', 'Change the endpoint', 'Approve the drug'],
      'Escalation is a series of decisions, each based on the cohort before.',
      'Skipping the review turns escalation into a schedule.',
    ),
  ],
};

export const w4Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
