import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 5. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w5-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'recruitment-specialist': [
    q(
      'recruitment-specialist',
      1,
      'recruitment-materials',
      'A study ad must…',
      [
        'Say it is research and be approved by the ethics committee',
        'Promise a cure',
        'Offer a large payment',
        'Hide the placebo',
      ],
      'Ads are part of the consent process and are reviewed like consent forms.',
      'Misleading ads are pulled and reported.',
    ),
    q(
      'recruitment-specialist',
      2,
      'patient-recruitment',
      'For a rare disease, the most productive recruitment channel is usually…',
      ['Patient organisations and referring specialists', 'Television ads', 'Billboards', 'Random mail'],
      'The community already knows who has the disease.',
      'Ad-heavy campaigns generate calls from people who cannot join.',
    ),
    q(
      'recruitment-specialist',
      3,
      'undue-influence',
      'Paying doctors a bonus per patient referred is a problem because…',
      ['It creates a conflict of interest', 'It is too cheap', 'Doctors refuse it', 'It slows recruitment'],
      "Finder's fees tempt referral of people who do not quite fit.",
      "Regulators treat finder's fees as undue influence.",
    ),
    q(
      'recruitment-specialist',
      4,
      'patient-recruitment',
      'Why does a recruitment plan address diversity?',
      [
        'So results apply to everyone who will take the medicine',
        'To satisfy marketing',
        'Regulators forbid it',
        'It is optional decoration',
      ],
      'A trial that enrols only one group tells you little about the others.',
      'Unrepresentative trials leave real patients with unknown risks.',
    ),
  ],
  'cra-monitor': [
    q(
      'cra-monitor',
      1,
      'sdv',
      'Source data verification means…',
      [
        'Comparing the database to the original clinic records',
        'Asking the coordinator if it is right',
        'Reading the protocol again',
        "Checking the drug's price",
      ],
      'The source is the truth; the database is a copy.',
      'Data never checked against source cannot be trusted.',
    ),
    q(
      'cra-monitor',
      2,
      'protocol-deviation',
      'A patient was dosed two days before signing consent. This is…',
      ['A serious deviation to report', 'Fine if the labs match', 'A minor note', 'Normal practice'],
      'Consent must come before any study procedure.',
      'Dosing before consent is a critical finding.',
    ),
    q(
      'cra-monitor',
      3,
      'monitoring-visit',
      'Signing a visit report without checking records…',
      [
        'Leaves deviations for an inspector to find',
        'Saves the sponsor money',
        'Is standard practice',
        'Improves data quality',
      ],
      'The monitor exists to find problems before inspectors do.',
      'Unfound deviations become inspection findings.',
    ),
    q(
      'cra-monitor',
      4,
      'sdv',
      'Which is a warning sign at a site?',
      [
        'Perfect data with no queries and no adverse events',
        'A documented late visit',
        'An open query',
        'A re-signed consent after an amendment',
      ],
      'Real data are messy; perfection suggests fabrication.',
      'Missing the too-clean pattern lets fraud into the trial.',
    ),
  ],
  'clinical-data-manager': [
    q(
      'clinical-data-manager',
      1,
      'data-query',
      'A weight of 16.2 kg for an adult should be…',
      ['Queried to the site', 'Accepted', 'Deleted', 'Rounded'],
      'Impossible values are queried and corrected from source.',
      'Unqueried values end up in the analysis.',
    ),
    q(
      'clinical-data-manager',
      2,
      'data-cleaning',
      'A blank field is…',
      ['Queried like any other problem', 'Ignored', 'Filled in by the data manager', 'Fine'],
      'The site enters the value from source or confirms it was not collected.',
      'Blanks become missing data.',
    ),
    q(
      'clinical-data-manager',
      3,
      'data-query',
      'A site answers a query with "as per source" and no value. You…',
      ['Send it back for a real answer', 'Close it', 'Enter a value yourself', 'Escalate to the regulator'],
      'Non-answers do not resolve queries.',
      'Accepting non-answers leaves errors in place.',
    ),
    q(
      'clinical-data-manager',
      4,
      'data-cleaning',
      'Closing queries without reviewing the answer…',
      [
        'Leaves wrong values marked as resolved',
        'Speeds the trial safely',
        'Is required by GCP',
        'Improves accuracy',
      ],
      'Review is what makes a query resolution real.',
      'Auto-closing quietly corrupts the dataset.',
    ),
  ],
  'medical-coder': [
    q(
      'medical-coder',
      1,
      'meddra',
      'MedDRA is used to code…',
      ['Adverse events and diagnoses', 'Drug prices', 'Site addresses', 'Statistical methods'],
      'A standard dictionary lets the same event be counted the same way everywhere.',
      'Inconsistent coding distorts safety tables.',
    ),
    q(
      'medical-coder',
      2,
      'whodrug',
      'WHODrug is used to code…',
      ['Medicines patients take', 'Lab units', 'Patient names', 'Hospital departments'],
      'Coded medicines make interactions searchable.',
      'Uncoded medicines hide interactions.',
    ),
    q(
      'medical-coder',
      3,
      'medical-coding',
      '"My heart was racing" should be coded as…',
      ['Palpitations', 'Myocardial infarction', 'Anxiety', 'Nothing'],
      'Code what was reported, not more and not less.',
      'Over- or under-coding both distort the safety profile.',
    ),
    q(
      'medical-coder',
      4,
      'medical-coding',
      "Accepting the auto-coder's first suggestion for every term…",
      ['Risks systematic miscoding', 'Is best practice', 'Is required', 'Improves accuracy'],
      'Auto-suggestions need a human check.',
      'Miscoded liver signals go unseen.',
    ),
  ],
  'pharmacovigilance-associate': [
    q(
      'pharmacovigilance-associate',
      1,
      'sae',
      'Which makes an event "serious"?',
      [
        'Hospitalisation, death, life-threat, disability or birth defect',
        'The patient being upset',
        'Any rash',
        "The investigator's opinion alone",
      ],
      'Seriousness follows a fixed definition, not severity.',
      'Misjudging seriousness breaks reporting deadlines.',
    ),
    q(
      'pharmacovigilance-associate',
      2,
      'susar',
      'A SUSAR is…',
      [
        'Serious, unexpected and possibly related to the drug',
        'Any serious event',
        'Any unexpected event',
        'A placebo reaction',
      ],
      'All three conditions must hold.',
      'Late SUSARs are the most serious pharmacovigilance failure.',
    ),
    q(
      'pharmacovigilance-associate',
      3,
      'expedited-reporting',
      'A fatal or life-threatening SUSAR must reach regulators within…',
      ['7 days', '30 days', '24 hours', '90 days'],
      'Other SUSARs have 15 days; sites report SAEs to the sponsor within 24 hours.',
      'Missing the clock is a regulatory finding.',
    ),
    q(
      'pharmacovigilance-associate',
      4,
      'causality',
      'A hospitalised patient might be on placebo. The SAE report…',
      ['Is still due within 24 hours', 'Waits for unblinding', 'Is not needed', 'Goes to marketing'],
      'Seriousness is judged now; causality and arm come later.',
      'Waiting to learn the arm breaks the 24-hour rule.',
    ),
  ],
};

export const w5Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
