import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 6. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w6-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'global-study-manager': [
    q(
      'global-study-manager',
      1,
      'protocol-amendment',
      'A protocol amendment in a 40-country trial needs…',
      [
        'Approval in each country before its sites use it',
        'One global approval',
        'No approval',
        "Only the sponsor's signature",
      ],
      'Regulators and ethics committees approve country by country.',
      'Sites on different versions produce data that cannot be pooled.',
    ),
    q(
      'global-study-manager',
      2,
      'enrolment-rate',
      'A country 40% behind on enrolment should first be…',
      ['Assessed for the cause, then given a plan', 'Closed', 'Ignored', 'Pushed to enrol anyone'],
      'Escalations run assess, plan, approve, execute.',
      'Pushing sites for speed trades enrolment for deviations.',
    ),
    q(
      'global-study-manager',
      3,
      'dsmb',
      'A DSMB request for an extra listing should be…',
      ['Prioritised and delivered', 'Declined', 'Delayed until the next quarter', 'Sent to marketing'],
      'A waiting committee delays the interim decision.',
      'Boards kept waiting delay decisions for every patient.',
    ),
    q(
      'global-study-manager',
      4,
      'phase-3',
      'Phase III trials exist mainly to…',
      [
        'Prove efficacy and safety at a scale regulators accept',
        'Find the first human dose',
        'Test a hypothesis in 20 people',
        'Set the price',
      ],
      'Large, controlled, usually across many countries.',
      'Skipping scale leaves regulators without proof.',
    ),
  ],
  'central-monitor': [
    q(
      'central-monitor',
      1,
      'risk-based-monitoring',
      'Risk-based monitoring means…',
      [
        'Focusing effort where errors are likely and important',
        'Never visiting sites',
        'Checking every data point',
        'Monitoring only big sites',
      ],
      'Central data review directs the travelling monitors.',
      'Uniform monitoring wastes effort where nothing is wrong.',
    ),
    q(
      'central-monitor',
      2,
      'key-risk-indicator',
      'A site with the fastest enrolment, zero queries and one fifth the average AE rate is…',
      ['An outlier needing an urgent visit', 'The best site', 'Normal', 'A site to reward'],
      'Too fast, too clean and too few events is the fabrication pattern.',
      'Fabricated data reach the analysis if nobody looks.',
    ),
    q(
      'central-monitor',
      3,
      'key-risk-indicator',
      'A site with a high but well-documented adverse event rate is…',
      ['Probably reporting properly', 'Fabricating', 'Dangerous', 'To be closed'],
      'Honest reporting produces higher event counts.',
      'Punishing honest reporting teaches sites to stop.',
    ),
    q(
      'central-monitor',
      4,
      'monitoring-visit',
      'Keeping the routine visit schedule despite an outlier…',
      [
        'Leaves suspect data in the analysis for months',
        'Saves money safely',
        'Is required',
        'Improves quality',
      ],
      'Triggered visits exist to act on signals now.',
      'Delayed action lets bad data spread.',
    ),
  ],
  'qa-auditor': [
    q(
      'qa-auditor',
      1,
      'audit-finding',
      'Fabricated patient data is graded…',
      ['Critical', 'Major', 'Minor', 'Observation'],
      'Unreliable data and possible harm define critical.',
      'Downgrading fabrication is itself a compliance failure.',
    ),
    q(
      'qa-auditor',
      2,
      'capa',
      'A CAPA is…',
      ['A plan to fix a finding and prevent recurrence', 'A type of audit', 'A regulator', 'A consent form'],
      'Corrective and preventive action follows major findings.',
      'Findings without CAPAs recur.',
    ),
    q(
      'qa-auditor',
      3,
      'audit',
      'The difference between an audit and an inspection is…',
      [
        'Audits are the sponsor checking itself; inspections are regulators checking the sponsor',
        'There is none',
        'Inspections are voluntary',
        'Audits are done by regulators',
      ],
      "A good audit finds the inspection's findings first.",
      'Confusing the two leads to unprepared inspections.',
    ),
    q(
      'qa-auditor',
      4,
      'delegation-log',
      'A nurse assessing adverse events before being added to the delegation log is…',
      ['A major finding', 'Fine', 'A minor note', 'Critical'],
      'Undelegated work is unauthorised work affecting data.',
      'Undelegated assessments can be excluded from analysis.',
    ),
  ],
  'dsmb-member': [
    q(
      'dsmb-member',
      1,
      'dsmb',
      'The DSMB tells the sponsor…',
      ['Only its recommendation', 'All unblinded results', 'The efficacy trend', 'Which arm is winning'],
      "The board protects the sponsor's blind.",
      'A sponsor that learns arm-level data cannot run the trial without bias.',
    ),
    q(
      'dsmb-member',
      2,
      'futility',
      'A futility boundary set at 20% conditional power means…',
      [
        'Stop only if the chance of success falls below 20%',
        'Stop if power is below 55%',
        'Stop at any time',
        'Never stop',
      ],
      'Boundaries set in advance keep decisions off hope and fear.',
      'Moving boundaries after seeing data is indefensible.',
    ),
    q(
      'dsmb-member',
      3,
      'interim-analysis',
      'A 4% versus 1% mild liver enzyme imbalance with no serious cases most likely warrants…',
      ['Continue with enhanced monitoring', 'Immediate termination', 'Ignoring it', 'Telling the press'],
      'Proportionate response to a signal below the boundary.',
      'Over- and under-reaction both harm patients.',
    ),
    q(
      'dsmb-member',
      4,
      'unblinding',
      'Whole-trial unblinding happens…',
      ['After database lock', 'At the first interim', 'Whenever the sponsor asks', 'Before enrolment ends'],
      'Lock first, codes second.',
      'Unblinding before lock taints every later change.',
    ),
  ],
  'database-lock-lead': [
    q(
      'database-lock-lead',
      1,
      'database-lock',
      'Database lock means…',
      [
        'No data can change afterwards; access is removed',
        'The database is backed up',
        'The sponsor sees results',
        'The study is published',
      ],
      'Lock is a signed, timestamped event.',
      'Every unlock must be justified and is scrutinised.',
    ),
    q(
      'database-lock-lead',
      2,
      'unblinding',
      'Randomization codes are released…',
      ['After the lock is signed', 'Before queries are resolved', 'At enrolment', 'To marketing'],
      'Codes after lock, so no result can influence the data.',
      'Codes before lock make later changes look like tampering.',
    ),
    q(
      'database-lock-lead',
      3,
      'sap',
      'The primary analysis is run…',
      [
        'Exactly as the SAP describes',
        'However the data suggest',
        'After choosing the best method',
        "By the sponsor's marketing team",
      ],
      'The analysis was fixed before the data.',
      'Adjusted analyses are not pre-specified.',
    ),
    q(
      'database-lock-lead',
      4,
      'data-cleaning',
      'Before lock, the safety and clinical databases must be…',
      ['Reconciled so every serious event matches', 'Deleted', 'Merged into one', 'Sent to the regulator'],
      'Every serious event must be identical in both.',
      'Mismatched safety data are a standard submission finding.',
    ),
  ],
  'statistical-programmer': [
    q(
      'statistical-programmer',
      1,
      'sdtm',
      'SDTM organises…',
      ['Collected data into standard domains', 'Analysis results', 'The protocol', 'Site contracts'],
      'The tabulation model: what happened, organised.',
      'Without SDTM, reviewers cannot use their tools.',
    ),
    q(
      'statistical-programmer',
      2,
      'adam',
      'ADaM datasets are…',
      ['Analysis-ready, derived from SDTM, traceable', 'Raw entries', 'Marketing data', 'Consent records'],
      'ADaM adds derived variables and populations for the SAP.',
      'Analysis straight from SDTM cannot be traced.',
    ),
    q(
      'statistical-programmer',
      3,
      'double-programming',
      'Double programming means…',
      [
        'A second programmer independently reproduces each output',
        'Running the code twice',
        'Using two languages',
        'Programming at double speed',
      ],
      'Two people, two programs, one answer.',
      'Skipping it ships arithmetic errors into the submission.',
    ),
    q(
      'statistical-programmer',
      4,
      'tlf',
      'Every number in a study report should come from…',
      ['A validated table, listing or figure', "The writer's memory", 'The press release', 'A spreadsheet'],
      'Traceability from report to table to dataset.',
      'Untraceable numbers are challenged at review.',
    ),
  ],
  'medical-writer': [
    q(
      'medical-writer',
      1,
      'csr',
      'The Clinical Study Report follows…',
      [
        'A fixed international structure (ICH E3)',
        'Whatever order reads best',
        'The marketing brief',
        "The sponsor's template only",
      ],
      'A fixed structure lets reviewers find everything.',
      'Non-standard reports are sent back.',
    ),
    q(
      'medical-writer',
      2,
      'post-hoc-analysis',
      'A post-hoc subgroup with a bigger effect should be…',
      [
        'Labelled exploratory, never presented as the result',
        'The headline',
        'Hidden',
        'Used as the primary endpoint',
      ],
      'Unplanned analyses are exploratory.',
      'Presenting post-hoc findings as primary is misconduct.',
    ),
    q(
      'medical-writer',
      3,
      'benefit-risk',
      'A good conclusion states…',
      [
        'Benefit and risk together, in proportion to the data',
        'Only the benefit',
        'Only the risk',
        '"Breakthrough cure"',
      ],
      'Conclusions match the evidence.',
      'Overselling undermines the whole submission.',
    ),
    q(
      'medical-writer',
      4,
      'csr',
      'Safety results in a CSR cover…',
      [
        'All events in both arms, with narratives for serious cases',
        'The placebo arm only',
        'Only mild events',
        'A summary sentence',
      ],
      'Complete by design.',
      'Selective safety reporting is a serious offence.',
    ),
  ],
};

export const w6Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
