import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 7. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w7-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'regulatory-affairs-lead': [
    q(
      'regulatory-affairs-lead',
      1,
      'ectd-modules',
      'Clinical study reports belong in eCTD Module…',
      ['5', '2', '3', '4'],
      'Module 5 is clinical; 4 nonclinical; 3 quality; 2 summaries.',
      'Misfiled reports are reports the reviewer cannot find.',
    ),
    q(
      'regulatory-affairs-lead',
      2,
      'nda',
      'The US marketing application is the…',
      ['NDA', 'IND', 'CTA', 'CSR'],
      'The IND asks to test; the NDA asks to sell.',
      'Confusing the two confuses the strategy.',
    ),
    q(
      'regulatory-affairs-lead',
      3,
      'maa',
      'The EU marketing application is the…',
      ['MAA', 'NDA', 'IND', 'SAP'],
      "The MAA is reviewed through the EMA's centralised procedure.",
      'Regional requirements differ; know which applies.',
    ),
    q(
      'regulatory-affairs-lead',
      4,
      'ectd-modules',
      'Module 2 contains…',
      ['Overviews and summaries', 'Raw datasets', 'Regional forms', 'Batch records'],
      "Module 2 is the reviewer's map to the rest.",
      'A weak Module 2 leaves 100,000 pages without a guide.',
    ),
  ],
  'submission-publisher': [
    q(
      'submission-publisher',
      1,
      'technical-validation',
      'Technical validation checks…',
      [
        'Files, links, formats and metadata against specifications',
        'Whether the drug works',
        'The price',
        'The marketing plan',
      ],
      'Automated checks run before and after submission.',
      'A failing file can reject the whole sequence.',
    ),
    q(
      'submission-publisher',
      2,
      'technical-validation',
      'An image-only scanned PDF is a problem because…',
      [
        'It is not searchable and cannot be bookmarked properly',
        'It is too colourful',
        'Regulators dislike images',
        'It is too small',
      ],
      'Reviewers must search and navigate documents.',
      'Unsearchable files fail validation.',
    ),
    q(
      'submission-publisher',
      3,
      'ectd',
      'The eCTD backbone is…',
      [
        'An XML structure that organises every document and its lifecycle',
        'A paper binder',
        'A spreadsheet',
        'A cover letter',
      ],
      "The backbone tells the reviewer's system where everything is.",
      'Wrong lifecycle attributes break future amendments.',
    ),
    q(
      'submission-publisher',
      4,
      'technical-validation',
      'Submitting without a pre-check…',
      [
        'Risks a public bounce and a moved filing date',
        'Saves time safely',
        'Is required',
        'Improves quality',
      ],
      'Pre-validation finds what the gateway would find.',
      'A bounced submission restarts the clock.',
    ),
  ],
  'health-authority-reviewer': [
    q(
      'health-authority-reviewer',
      1,
      'filing-review',
      'The filing review decides…',
      [
        'Whether the application is complete enough to review fully',
        'Whether the drug is approved',
        "The drug's price",
        'The marketing claims',
      ],
      'About 60 days in the US; the day-74 letter reports the outcome.',
      'Missing pieces mean refuse-to-file.',
    ),
    q(
      'health-authority-reviewer',
      2,
      'benefit-risk',
      "When a sponsor's summary and its data disagree, a reviewer should…",
      [
        'Ask a precise question with a deadline',
        'Accept the summary',
        'Reject the application',
        'Ignore the data',
      ],
      'Questions resolve gaps; verdicts come after answers.',
      'Summaries accepted at face value miss signals.',
    ),
    q(
      'health-authority-reviewer',
      3,
      'advisory-committee',
      'Patient testimony at an advisory committee is…',
      [
        'Evidence about what benefit means to patients, not a vote',
        'The deciding factor',
        'Irrelevant',
        'A marketing tool',
      ],
      'It informs the benefit side of the judgement.',
      'Ignoring or over-weighting it both distort decisions.',
    ),
    q(
      'health-authority-reviewer',
      4,
      'complete-response-letter',
      'A complete response letter means…',
      [
        'The application cannot be approved as submitted',
        'The drug is approved',
        'The review is complete and positive',
        'The sponsor must withdraw',
      ],
      'It lists what would be needed for approval.',
      'Unneeded CRLs delay medicines for no safety gain.',
    ),
  ],
  'inspection-readiness-lead': [
    q(
      'inspection-readiness-lead',
      1,
      'gcp-inspection',
      'A document the sponsor cannot produce during inspection is…',
      ['Treated as if it never existed', 'Assumed to be fine', 'Not important', 'Requested by email later'],
      'If it is not in the file, it did not happen.',
      '"Not provided" is a finding.',
    ),
    q(
      'inspection-readiness-lead',
      2,
      'gcp-inspection',
      'Reconstructing a missing document during an inspection is…',
      ['Worse than admitting it is missing', 'Good practice', 'Required', 'Harmless'],
      'Inspectors notice dates and become suspicious of everything else.',
      'Reconstructed records turn a gap into a fraud question.',
    ),
    q(
      'inspection-readiness-lead',
      3,
      'tmf',
      'Inspection requests are answered from…',
      ['The Trial Master File', 'Staff laptops', 'Memory', 'The press office'],
      'Retrieval from the official file, checked and logged.',
      'Documents from laptops raise questions about what else lives there.',
    ),
    q(
      'inspection-readiness-lead',
      4,
      'capa',
      'Showing the inspector a finding with its CAPA…',
      ['Demonstrates the finding was handled', 'Admits guilt', 'Is forbidden', 'Delays the inspection'],
      'A documented corrective plan is a handled finding.',
      'Findings without CAPAs become inspection findings.',
    ),
  ],
  'labeling-specialist': [
    q(
      'labeling-specialist',
      1,
      'boxed-warning',
      'A boxed warning is used for…',
      [
        'Serious or life-threatening risks',
        'Minor side effects',
        'Marketing highlights',
        'Dosing instructions',
      ],
      'The most prominent warning a US label carries.',
      'Burying serious risks in tables leads to harm.',
    ),
    q(
      'labeling-specialist',
      2,
      'indication',
      'The indication on a label should match…',
      [
        'The population and disease the trials tested',
        'The largest possible market',
        "The sponsor's hopes",
        "Competitors' labels",
      ],
      'Evidence sets the boundary.',
      'Over-broad indications are refused or recalled.',
    ),
    q(
      'labeling-specialist',
      3,
      'contraindication',
      'A contraindication names…',
      ['Who must not take the medicine', 'The recommended dose', 'The price', 'The manufacturer'],
      'Where risk clearly outweighs any benefit.',
      'Without it, the drug reaches those it can hurt most.',
    ),
    q(
      'labeling-specialist',
      4,
      'prescribing-information',
      'Marketing may claim…',
      [
        'Only what the approved label says',
        'Anything supported by any study',
        'Whatever sells',
        'What competitors claim',
      ],
      'The label is the boundary of promotion.',
      'Off-label promotion is illegal.',
    ),
  ],
};

export const w7Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
