import type { KnowledgeCheck, QuizQuestion } from '../types';

/** Test Yourself for World 8. Optional; never gates progress. */
const q = (
  roleId: string,
  n: number,
  conceptId: string,
  prompt: string,
  options: [string, string, string, string],
  explanation: string,
  consequence: string,
): QuizQuestion => ({
  id: `w8-${roleId}-q${n}`,
  roleId,
  conceptId,
  prompt,
  options: options.map((text, i) => (i === 0 ? { text, correct: true } : { text })),
  explanation,
  consequence,
});

const byRole: Record<string, QuizQuestion[]> = {
  'manufacturing-supply-lead': [
    q(
      'manufacturing-supply-lead',
      1,
      'process-validation',
      'Process validation typically requires…',
      [
        'Consecutive full-scale batches that pass specification',
        'One small test batch',
        'A marketing plan',
        'A press release',
      ],
      'Validation proves the commercial process, not the clinical one.',
      'Unvalidated processes fail pre-approval inspection.',
    ),
    q(
      'manufacturing-supply-lead',
      2,
      'launch-stock',
      'Launch stock should be…',
      [
        'Released, in date, and sized to the first months of demand',
        'As large as possible',
        'Made after approval',
        'Unreleased to save time',
      ],
      'Too little means shortage; too much means expiry.',
      'Shortages at launch harm patients waiting for treatment.',
    ),
    q(
      'manufacturing-supply-lead',
      3,
      'gmp',
      'GMP applies to…',
      ['Every commercial batch, forever', 'Only clinical batches', 'Only the first year', 'Only in the US'],
      'Good Manufacturing Practice governs all production for sale.',
      'A GMP failure can trigger a recall.',
    ),
    q(
      'manufacturing-supply-lead',
      4,
      'risk-management-plan',
      'Why budget contingency in scale-up?',
      ['A failed batch at scale-up is normal', 'Regulators require it', 'To buy equipment', 'To pay bonuses'],
      'One failed batch is expected; the budget absorbs it.',
      'No contingency turns one failure into a missed launch.',
    ),
  ],
  'market-access-specialist': [
    q(
      'market-access-specialist',
      1,
      'hta',
      'A health technology assessment decides…',
      [
        'Whether a medicine is worth its cost to the health system',
        'Whether it is safe',
        'Whether it is patented',
        'Whether doctors like it',
      ],
      'HTA verdicts shape reimbursement in many countries.',
      'A "not cost-effective" verdict blocks access.',
    ),
    q(
      'market-access-specialist',
      2,
      'reimbursement',
      'Reimbursement means…',
      [
        'A payer agrees to cover the medicine at an agreed price',
        'The company refunds patients',
        'The regulator pays',
        'Doctors are paid',
      ],
      'Coverage, price and eligible patients are negotiated.',
      'Approved medicines without reimbursement reach few patients.',
    ),
    q(
      'market-access-specialist',
      3,
      'value-dossier',
      'A value dossier argues…',
      [
        'Clinical benefit, quality of life and cost versus alternatives',
        'Marketing slogans',
        'The manufacturing process',
        "The company's share price",
      ],
      'It is the evidence behind the price.',
      'A weak value case leads to refusal or deep discounts.',
    ),
    q(
      'market-access-specialist',
      4,
      'payer',
      'Pricing far above the value case usually…',
      [
        'Excludes patients through restricted coverage',
        'Reaches more patients',
        'Is required by law',
        'Pleases HTA bodies',
      ],
      'Payers restrict use when price exceeds judged value.',
      'A price that excludes patients defeats the point of the medicine.',
    ),
  ],
  'brand-marketing-manager': [
    q(
      'brand-marketing-manager',
      1,
      'off-label',
      'Promoting a medicine for an unapproved population is…',
      ['Illegal off-label promotion', 'Fine if doctors ask', 'Allowed with a footnote', 'Best practice'],
      'Doctors may prescribe off-label; companies may not promote it.',
      'Off-label promotion brings fines and warning letters.',
    ),
    q(
      'brand-marketing-manager',
      2,
      'fair-balance',
      'Fair balance requires…',
      [
        'Risks presented with prominence comparable to benefits',
        'Risks in small print',
        'Benefits only',
        'A disclaimer',
      ],
      'The warning belongs beside the claim.',
      'Unbalanced promotion is the most common violation.',
    ),
    q(
      'brand-marketing-manager',
      3,
      'promotional-review',
      'Before a campaign runs it must pass…',
      ['Medical, legal and regulatory review', 'A sales meeting', 'Nothing', 'Investor approval'],
      'Every piece is reviewed before use.',
      'Unreviewed claims cause recalls of campaigns.',
    ),
    q(
      'brand-marketing-manager',
      4,
      'prescribing-information',
      'Marketing may claim…',
      [
        'Only what the approved label says, with substantiation',
        'Anything a study suggested',
        'What competitors claim',
        'Whatever sells',
      ],
      'The label is the boundary.',
      'Claims beyond the label are off-label.',
    ),
  ],
  'medical-science-liaison': [
    q(
      'medical-science-liaison',
      1,
      'non-promotional',
      'An MSL answering an unsolicited off-label question should…',
      [
        'Give balanced scientific evidence without recommending',
        'Refuse entirely',
        'Encourage the use',
        'Refer to sales',
      ],
      'Scientific exchange is allowed; promotion is not.',
      'Encouraging off-label use through MSLs is treated as worse than an ad.',
    ),
    q(
      'medical-science-liaison',
      2,
      'spontaneous-report',
      'An MSL hears of an adverse event from a doctor. They must…',
      [
        'Report it to pharmacovigilance within one business day',
        'Ignore it if managed',
        'Wait for the quarterly review',
        'Tell marketing',
      ],
      'Every employee is a reporting channel.',
      'Unreported events delay signals by a year.',
    ),
    q(
      'medical-science-liaison',
      3,
      'medical-information',
      'A patient asks an MSL about her own treatment. The MSL should…',
      [
        'Explain the label and refer her to her doctor',
        'Give personal medical advice',
        'Say nothing',
        'Suggest skipping tests',
      ],
      'Individual advice belongs to the treating doctor.',
      'Company staff advising patients directly is a policed boundary.',
    ),
    q(
      'medical-science-liaison',
      4,
      'non-promotional',
      'MSLs are kept separate from sales because…',
      [
        'Doctors must be able to trust that they are not selling',
        'They cost less',
        'Regulators dislike scientists',
        'Sales teams are larger',
      ],
      'Independence from sales targets is the point.',
      'Mixing the roles turns science into promotion.',
    ),
  ],
  'sales-representative': [
    q(
      'sales-representative',
      1,
      'detailing',
      'Detailing must use…',
      ['Approved materials only', "The rep's own slides", 'Whatever persuades', 'Competitor data'],
      'Only reviewed materials are approved claims.',
      'Improvised claims are unreviewed claims.',
    ),
    q(
      'sales-representative',
      2,
      'fair-balance',
      'A rep who mentions the boxed warning only if asked is…',
      ['Making a misleading presentation', 'Being efficient', 'Following best practice', 'Complying'],
      'The warning is part of the claim, not optional context.',
      'Unbalanced detailing generates regulator complaints.',
    ),
    q(
      'sales-representative',
      3,
      'inducement',
      "Paying a doctor's conference travel is…",
      ['An inducement, prohibited', 'A courtesy', 'Required', 'Fine if small'],
      'Anything of value to influence prescribing is an inducement.',
      'Inducements are bribery under anti-corruption law.',
    ),
    q(
      'sales-representative',
      4,
      'promotional-review',
      'A comparative claim ("better than drug X") requires…',
      ['Head-to-head evidence', 'Confidence', 'A footnote', 'Sales approval'],
      'No comparison data, no comparison claim.',
      'Unsupported comparisons are false advertising.',
    ),
  ],
  'signal-detection-scientist': [
    q(
      'signal-detection-scientist',
      1,
      'signal-detection',
      'A safety signal is…',
      [
        'A pattern suggesting a new or changed risk that needs assessment',
        'Any single report',
        'A marketing metric',
        'A trial endpoint',
      ],
      'Signals are validated before they become label changes.',
      'Missed signals harm thousands before the label changes.',
    ),
    q(
      'signal-detection-scientist',
      2,
      'disproportionality',
      'Nine reports of an event where one is expected is…',
      ['Disproportionate: a statistical signal', 'Normal', 'Irrelevant', 'A marketing opportunity'],
      'Disproportionality compares observed with expected reporting.',
      'Ignoring disproportionate reporting delays action.',
    ),
    q(
      'signal-detection-scientist',
      3,
      'causality',
      'Recurrence of an event when a drug is restarted is called…',
      ['Positive rechallenge', 'Placebo effect', 'Coincidence', 'Background rate'],
      'Rechallenge is strong causality evidence.',
      'Rechallenge cases left out understate risk.',
    ),
    q(
      'signal-detection-scientist',
      4,
      'spontaneous-report',
      'Why do post-market reports find risks trials missed?',
      [
        'Far more patients are exposed, so rare events appear',
        'Trials are dishonest',
        'Reports are more accurate',
        'Regulators demand it',
      ],
      'One in 10,000 is invisible in a trial of 1,000.',
      'Assuming trials found everything leaves rare harms unwatched.',
    ),
  ],
  'rwe-lead': [
    q(
      'rwe-lead',
      1,
      'phase-4',
      'A Phase IV study is run…',
      [
        'After approval, to answer questions the earlier trials could not',
        'Before Phase I',
        'Only for marketing',
        'Instead of Phase III',
      ],
      'Often required by the regulator as a condition of approval.',
      'Skipped post-approval studies leave risks unquantified.',
    ),
    q(
      'rwe-lead',
      2,
      'rwe',
      'Real-world evidence comes from…',
      [
        'Registries, health records and routine care data',
        'Social media only',
        'Press coverage',
        'Sales figures',
      ],
      'Data from patients actually taking the drug.',
      'Without RWE, rare events stay invisible.',
    ),
    q(
      'rwe-lead',
      3,
      'rwe',
      'Why include a comparator group in a post-approval safety study?',
      [
        'To separate drug effects from the disease itself',
        'To increase sample size',
        'Regulators forbid it otherwise',
        'To reduce cost',
      ],
      'Matched comparison shows excess risk.',
      'Uncontrolled counts produce panic or false reassurance.',
    ),
    q(
      'rwe-lead',
      4,
      'post-approval-commitment',
      'Publishing a safety study only if favourable is…',
      ['Hiding a risk', 'Standard practice', 'Required', 'Efficient'],
      'Commitments include reporting whatever the result.',
      "Unpublished safety data have ended companies' credibility.",
    ),
  ],
};

export const w8Knowledge: KnowledgeCheck[] = Object.entries(byRole).map(([roleId, questions]) => ({
  id: `kc-${roleId}`,
  roleId,
  questions,
}));
